### ISSUE TITLE
Yubikey 5 NFC, requestConnection Fido throws DEVICE_INELIGIBLE

### ISSUE THREAD

**Issue by ospfranco** [Yubico/yubikit-android#130]
Hi, I'm facing an issue on some android devices when I try to call the function:

```kotlin
device.requestConnection(FidoConnection::class.java) {
```

It throws a `com.yubico.yubikit.fido.client.ClientError: DEVICE_INELIGIBLE (code 4)` on some android devices but not on others.

Is there something I can do to fix/detect the problem before it happens?

**Comment by ospfranco** [comment]
I was using 2.4.0-beta1. I just bumped to 2.5.0 and waiting for feedback to see if it still fails.

**Comment by ospfranco** [comment]
Seems 2.5.0 fixes the issue. Thanks!

**Comment by AdamVe** [comment]
Thanks for reaching out, don't hesitate to contact us if you have any questions.
