### ISSUE TITLE
FIDO2 makeCredential fails with `UserVerificationRequirement.PREFERRED` over NFC

### ISSUE THREAD

**Issue by eadwu** [Yubico/yubikit-android#150]
WebAuthn implys it should just allow it to pass

preferred
This value indicates that the Relying Party prefers user verification for the operation if possible, but will not fail the operation if the response does not have the UV flag set.

`UserVerificationRequirement.DISCOURAGED` works just fine though.

**Comment by AdamVe** [comment]
Thank you for reporting 👍🏻

**Comment by eadwu** [comment]
The error is 
```
failed to generate credential: com.yubico.yubikit.fido.client.ClientError: BAD_REQUEST (code 2) - User verification not configured
```

Code is same as in https://github.com/Yubico/yubikit-android/issues/115#issuecomment-1893996236

**Comment by eadwu** [comment]
I want the opposite behavior of just having verification if it exists but it isn't necessary at all, I'll fallback to DISCOURAGED manually if it fails then.
