### ISSUE TITLE
getCredentialManager() without needing PIN?

### ISSUE THREAD

**Issue by eadwu** [Yubico/yubikit-android#157]
https://github.com/Yubico/yubikit-android/issues/115 should be implying that it is possible to create resident keys without a PIN, but I cannot find the resident keys without a PIN since the method needs a PIN. 

However, it is not possible to list all the resident metadata without a PIN? Adding a PIN after-the-fact lists all the resident keys as expected.

**Comment by AdamVe** [comment]
Credential Management requires pinUvAuthToken, see https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-errata-20220621.html#getCredsMetadata. Without it you will not be able to list/manage discoverable keys on the authenticator.

**Comment by eadwu** [comment]
Got it, I'll just store the mappings for metadata on the app itself then as a backup in this case if a PIN isn't provided.
