### ISSUE TITLE
OTPListener interface not accessible outside the com.yubico.yubikit.otp package

### ISSUE THREAD

**Issue by tonydailallscripts** [Yubico/yubikit-android#19]
I created a Xamarin binding for Yubikit and otp packages.  I am unable to implement the interface since it does not have an access modifier and it defaults to private.  I made it public in my local repository and it resolves the issue.

**Comment by imakhalova** [comment]
Valid point. Please feel free to submit pull request with this change.

**Comment by tonydailallscripts** [comment]
I do not have commit privileges.

**Comment by ludwrd** [comment]
Thank you for your feedback! We are investigating if the change would have any unwanted effects and will get back to you shortly. 

Feel free to reach out if you have any further feedback or questions.

**Comment by dainnilsson** [comment]
After some investigation we determined that this class and some other related ones shouldn't be extended by the user, and some access modifiers have been changed to reflect that.
