### ISSUE TITLE
Duplicate entries in the preferences (settings.xml)

### ISSUE THREAD

**Issue by bjvetter** [Yubico/yubikit-android#2]
There are multiple categories named "OATH features". A couple of the same key names are the same (use_touch and truncate_totp) in each of the categories. Is this an oversight or is there some reason for the various categories and why they share key names or is this something that is still in process/not working yet?

**Comment by imakhalova** [comment]
Thank you for sharing, this looks like just copy paste mistake, disregard second/duplicated records. We will fix it.

**Comment by imakhalova** [comment]
Addressed in https://github.com/Yubico/yubikit-android/pull/4
