### ISSUE TITLE
It's possible write NDEF Message in Yubikey ?

### ISSUE THREAD

**Issue by ukieTux** [Yubico/yubikit-android#37]
I have tried to Write NDEF Message to Yubikey , from this [reference](https://developer.android.com/guide/topics/connectivity/nfc/nfc.html#aar)

I need to add new `mime type` or `createApplicationRecord` to automatically launch NFCReader from my apps. Even if i'm using android:scheme="https" it's not working if **Microsoft Edge** was Installed 

I was trying to write but get IOException
![image](https://user-images.githubusercontent.com/1531684/100968394-39f48b80-356c-11eb-967c-d597756e9313.png)

**Comment by dainnilsson** [comment]
No, writing the NDEF tag on a YubiKey is not possible.

**Comment by ukieTux** [comment]
![image](https://user-images.githubusercontent.com/1531684/101446907-2330a900-395f-11eb-87ee-8d7122e7536e.png)

So i can't change url like **YubiKey Personalization Tool** App ? It's only can change from PC?
