### ISSUE TITLE
Security Protocol with offline support

### ISSUE THREAD

**Issue by ukieTux** [Yubico/yubikit-android#38]
Hi, which security protocol support when i'm in offline,
I was try OTP and PIV, it's need internet connection. I tried it on Demo Application and should register device on Yubicloud and setting device using **yubikey personalization tool**  to enable OTP/PIV support . Any suggest ? 
Thanks

**Comment by dainnilsson** [comment]
It really depends on what you're authenticating against. If it's a remote server, then you won't get around the issue of needing Internet connectivity. Both OTP and PIV _can_ be used fully offline, but it really depends on your use case.
