### ISSUE TITLE
Missing pending indent mutability flag on USB permission intent

### ISSUE THREAD

**Issue by v3rm0n** [Yubico/yubikit-android#48]
Targeting S+ (version 10000 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent. Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.

Problem is at https://github.com/Yubico/yubikit-android/blob/master/android/src/main/java/com/yubico/yubikit/android/transport/usb/UsbDeviceManager.java#L95

**Comment by AdamVe** [comment]
Hi, thank you for your report. The issue you mention is solved in our `next` branch, which is the development branch for the next version of yubikit-android.

We are evaluating whether or not to release a patch version of the sdk to address this issue before `next` is released.

**Comment by AdamVe** [comment]
This has been fixed with release 2.1.0, I am closing this issue.
