### ISSUE TITLE
Read Yubico OTP throws error

### ISSUE THREAD

**Issue by nejcburic** [Yubico/yubikit-android#69]
I've been checking AndroidDemo project in the repository. Since You updated Android dependencies, createIntent method in ActivityResultContract changed parameter input from nullable to non nullable. It throws error when trying to request otp.

Test App:
- open YubiOTP screen
- tap read yubico otp button

Source code:
- YubiOtpFragment, OtpContract class.

**Comment by AdamVe** [comment]
Hi, thanks for reporting this issue, I will review this asap.

**Comment by nejcburic** [comment]
Cool. Waiting for the new release
