### ISSUE TITLE
Fido2 PIN on Android

### ISSUE THREAD

**Issue by mattaojie** [Yubico/yubikit-android#71]
Does android fido2 support PIN?

**Comment by AdamVe** [comment]
AFAIK Android FIDO2 only uses CTAP1(FIDO2/U2F) protocol which does not support PIN. You need CTAP2 for this functionality.

Please refer to official FIDO2 API for Android https://developers.google.com/identity/fido/android/native-apps. Yubikit for Android supported a subset of the FIDO2 functionality in pre-release versions only.

You can find more information about CTAP versions at https://www.yubico.com/resources/glossary/ctap/
