### ISSUE TITLE
[Android 13][OtpActivity] NFC scan hangs after detecting yubikey

### ISSUE THREAD

**Issue by marcin-michalek-miquido** [Yubico/yubikit-android#79]
Hello,

I think there is a bug in the SDK on Andorid 13.
I use the SDK UI (OtpActivity) + activity result callback.

I prepared a minimal repo that reproduces the issue:
https://github.com/marcin-michalek-miquido/yubikoAndroid13

1) I click "scan"
2) The SDK dialog appears
3) I put a NFC key in range
4) SDK dialog detects it (label changes to "Remove key" + a sound)
5) SDK dialog freezes on that state not returning the result

Expected:
5) The SDK dialog closes and notifies the result callback in activity

Note: on the same devices when I plug the Yubikey using USB C the SDK works as expected - the issue is only with NFC.

So far it happens only on Android 13 (tested on Pixel 6 Pro and Pixel 5).
Also tested the same app from above repo on Android 12 and 11 using NFC and it works as expected.

Could you please confirm / fix?

**Comment by AdamVe** [comment]
Thanks for reporting, I can reproduce this in the AndroidDemo SDK demo application in master. 
I confirm your report that this occurs only on devices running Android 13.

**Comment by marcin-michalek-miquido** [comment]
Great, thanks for a fast fix! Do you plan to release a new artifact version soon?

**Comment by AdamVe** [comment]
We are hoping to make a release sometime in January 2023.

**Comment by AdamVe** [comment]
Fixed in release [2.2.0](https://github.com/Yubico/yubikit-android/releases/tag/2.2.0)
