### ISSUE TITLE
PivSession::generateKey do not store private key in Yubikey

### ISSUE THREAD

**Issue by Chralu** [Yubico/yubikit-android#81]
Hello,

PIV key generation behavior seems odd to me. 

When generating a PIV key in a given slot, I would expect the private key to be securely stored in the Yubikey.
But if I try to retrieve the generated key certificate (through `PivSession::getCertificate` or using [YubikitManager](https://www.yubico.com/support/download/yubikey-manager/)), PIV key slot is empty.

Is it the intended behavior ? In such case, what is the purpose of the `PivSession::generateKey` method ?

Thanks for your help 🙏

<details>
<summary>Key generation code example : </summary>

```kotlin
yubikitManager.startNfcDiscovery(NfcConfiguration(), activity) { device ->
      device.requestConnection(SmartCardConnection::class.java) { connectionResult ->
          val connection = connectionResult.getValue()
          val piv = PivSession(connection)

          piv.authenticate(
              managementKeyType,
              managementKey,
          )
          piv.verifyPin(
              pin.toCharArray()
          )
          val publicKey = piv.generateKey(
              Slot.SIGNATURE,
              KeyType.ECCP256,
              PinPolicy.DEFAULT,
              TouchPolicy.DEFAULT,
          )
      }
  }
```

</details>

<details>
<summary>Certificate retrieval code example :</summary>

```kotlin
yubikitManager.startNfcDiscovery(NfcConfiguration(), activity) { device ->
    device.requestConnection(SmartCardConnection::class.java) { connectionResult ->
        val connection = connectionResult.getValue()
        val piv = PivSession(connection)
        piv.verifyPin(
            pin.toCharArray()
        )
        val certificate = piv.getCertificate(Slot.SIGNATURE)
    }
}
```
</details>

**Comment by dainnilsson** [comment]
Keys and certificates are separate objects, independent of each other. If you want to be able to get a certificate, you will first need to store a certificate.

**Comment by Chralu** [comment]
Thanks for the explaination.
